let mockApartments = [
  {
    id: 1,
    street: "101 Rimrock",
    unit: "9A",
    city: "San Diego",
    state: "CA",
    square_footage: 500,
    price: "1800",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "Yes",
    image: "http://tinyurl.com/bdf8wvhj",
    user_id: 1
  },
  {
    id: 2,
    street: "720 Second Avenue",
    unit: "508",
    city: "San Diego",
    state: "CA",
    square_footage: 700,
    price: "2500",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "Yes",
    image: "http://tinyurl.com/yc2c33b7",
    user_id: 1
  },
  {
    id: 3,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 1.0,
    pets: "Small Pets Only",
    image: "http://tinyurl.com/c2jcztze",
    user_id: 2
  },
  {
    id: 4,
    street: "88 Broadway",
    unit: "1204",
    city: "San Francisco",
    state: "CA",
    square_footage: 850,
    price: "3400",
    bedrooms: 2,
    bathrooms: 2.5,
    pets: "No",
    image: "http://tinyurl.com/3raypd5x",
    user_id: 1
  },
  {
    id: 5,
    street: "500 Park Boulevard",
    unit: "45B",
    city: "Chicago",
    state: "IL",
    square_footage: 620,
    price: "2200",
    bedrooms: 1,
    bathrooms: 1.0,
    pets: "Yes",
    image: "http://tinyurl.com/ycx4rjbr",
    user_id: 2
  },
  {
    id: 6,
    street: "2300 Pine Street",
    unit: "3A",
    city: "Philadelphia",
    state: "PA",
    square_footage: 780,
    price: "2100",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "Yes",
    image: "http://tinyurl.com/39rvdyec",
    user_id: 1
  },
  {
    id: 7,
    street: "600 Wharf Ave",
    unit: "18",
    city: "Seattle",
    state: "WA",
    square_footage: 540,
    price: "1900",
    bedrooms: 1,
    bathrooms: 1.0,
    pets: "Small Pets Only",
    image: "http://tinyurl.com/5de4tr4m",
    user_id: 2
  },
  {
    id: 8,
    street: "88 West End",
    unit: "8C",
    city: "New York",
    state: "NY",
    square_footage: 1100,
    price: "4500",
    bedrooms: 3,
    bathrooms: 2.0,
    pets: "No",
    image: "http://tinyurl.com/3dsvjjb6",
    user_id: 1
  },
  {
    id: 9,
    street: "320 Elm Street",
    unit: "5A",
    city: "Austin",
    state: "TX",
    square_footage: 650,
    price: "2300",
    bedrooms: 1,
    bathrooms: 1.5,
    pets: "Yes",
    image: "http://tinyurl.com/2fcwrzd5",
    user_id: 2
  },
  {
    id: 10,
    street: "2020 Pinehurst Road",
    unit: "17",
    city: "Los Angeles",
    state: "CA",
    square_footage: 900,
    price: "3100",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "Yes",
    image: "http://tinyurl.com/28jayty3",
    user_id: 1
  }
]

export default mockApartments